{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "24b645a0-6e68-4bbf-b896-e237d5bf91e1",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "expected 'except' or 'finally' block (4098549572.py, line 64)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 64\u001b[1;36m\u001b[0m\n\u001b[1;33m    st.success('Dataset downloaded, cleaned and validated successfully.')\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m expected 'except' or 'finally' block\n"
     ]
    }
   ],
   "source": [
    "#Main Streamlit App code \n",
    "#This turns the ONS pipeline python code into a web app\n",
    "\n",
    "import io #makes downloaded bytes treated like a file\n",
    "from datetime import datetime, timezone\n",
    "import pandas as pd\n",
    "import requests #allows downloads CSV files from the internet\n",
    "import streamlit as st #use to create the web app interface\n",
    "\n",
    "#functions from python notebook: ONS consumer price indices pipeline\n",
    "from ons_dataset_app_functions import (\n",
    "    get_latest_version_metadata,\n",
    "    find_csv_download_url,\n",
    "    clean_dataset,\n",
    "    validate_dataset,\n",
    ")  \n",
    "\n",
    "#Page setup\n",
    "\n",
    "#Browser tab title, icon and page layout\n",
    "st.set_page_config(\n",
    "    page_title='ONS API Pipeline Consumer Price Indices',\n",
    "    page_icon ='📊',\n",
    "    layout='wide',\n",
    ")\n",
    "\n",
    "#App Title\n",
    "st.title('ONS API Pipeline Consumer Price Indices')\n",
    "\n",
    "#App Description\n",
    "st.write(\n",
    "    'Downloads the latest ONS dataset on Consumer Price Indices, cleans and validates,'\n",
    "    'it will provide the raw and processed CSV files.'\n",
    ")\n",
    "\n",
    "#User Input\n",
    "#Text box where user can type an ONS dataset ID\n",
    "#The ONLY value for now is cpih01\n",
    "\n",
    "dataset_id = st.text_input(\n",
    "    'ONS dataset ID',\n",
    "    value='cpih01',\n",
    "    help='Only available dataset (for now) is: cpih01'\n",
    ")\n",
    "\n",
    "#Creates button that will run the pipeline\n",
    "run_button = st.button('Get latest ONS dataset')\n",
    "\n",
    "#Main app LOGIC\n",
    "\n",
    "#This block runs only when the user clicks the button\n",
    "if run_button:\n",
    "    try:\n",
    "        with st.spinner('Getting latest dataset fron ONS...'):\n",
    "            latest_metadata = get_latest_version_metadata(dataset_id) #get metadata for latest version\n",
    "            csv_url = find_csv_download_url(latest_metadata) #find download url for csv inside metadata\n",
    "            response= requests.get(csv_url, timeout=60) #download csv file from url\n",
    "            response.raise_for_status() #Raise an error if download fail\n",
    "            raw_csv_bytes = response.content #store downloaded raw csv content as bytes\n",
    "            raw_df = pd.read_csv(io.BytesIO(raw_csv_bytes)) #convert raw bytes into file-like object then read as pandas df\n",
    "            cleaned_df = clean_dataset(raw_df) #clean dataset using pre existing function\n",
    "            validate_dataset(cleaned_df) #validate using pre exisiting function\n",
    "            processed_csv_bytes = cleanded_df.to_csv(index=False).encode(\"utf-8\")\n",
    "            timestamp = datetime.now(timezone.utc).strftime(\"%Y%m%d_%H%M%S\")\n",
    "\n",
    "    #If everything worked, show success message\n",
    "    st.success('Dataset downloaded, cleaned and validated successfully.')\n",
    "\n",
    "    #Show a small preview of the processed dataset\n",
    "    st.subheader('Preview of processed data')\n",
    "    st.dataframe(cleaned_df.head(10))\n",
    "\n",
    "    #Create two columns so the download buttons sit side by side.\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    # First column: raw CSV download button\n",
    "    with col1:\n",
    "        st.download_button(\n",
    "            label='Download raw CSV',\n",
    "            data= raw_csv_bytes,\n",
    "            file_name = f'{dataset_id}_{timestamp}_raw.csv',\n",
    "            name='text/csv',\n",
    "        )\n",
    "\n",
    "    # Second column: processed CSV download button\n",
    "    with col2:\n",
    "        st.download_button(\n",
    "            label='Download processed CSV',\n",
    "            data=processed_csv_bytes,\n",
    "            file_name=f'{dataset_id}_{timestamp}_processed.csv',\n",
    "            mime='text/csv',\n",
    "        )\n",
    "\n",
    "    # Show the original ONS source CSV URL in an expandable section\n",
    "    #for tranparency and debugging\n",
    "    with st.expander('Source CSV URL'):\n",
    "        st.write(csv_url)\n",
    "\n",
    "# If anything goes wrong, show the error in the streamlit app\n",
    "    except Exception as error:\n",
    "        st.error('Something went wrong.')\n",
    "        st.exception(error)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
